//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGuard.Phone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGuard.Phone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AboutView_Pivot_Contact {
            get {
                return ResourceManager.GetString("AboutView_Pivot_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string AboutView_Pivot_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AboutView_Pivot_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks To.
        /// </summary>
        public static string AboutView_Pivot_ThanksTo {
            get {
                return ResourceManager.GetString("AboutView_Pivot_ThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SmartGuard.
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got any questions?
        ///You can write us at info@smartguard.com to ask anything you want about this application..
        /// </summary>
        public static string AboutView_Txt_Contact {
            get {
                return ResourceManager.GetString("AboutView_Txt_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your location.
        /// </summary>
        public static string AboutView_Txt_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AboutView_Txt_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, I want to thank my college professors: Rosa Flores and Brigida Carvajal who helped me with as consultants during the whole process..
        /// </summary>
        public static string AboutView_Txt_ThanksTo {
            get {
                return ResourceManager.GetString("AboutView_Txt_ThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AppBar_Add {
            get {
                return ResourceManager.GetString("AppBar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions.
        /// </summary>
        public static string AppBar_Directions {
            get {
                return ResourceManager.GetString("AppBar_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start intense mode.
        /// </summary>
        public static string AppBar_Intense {
            get {
                return ResourceManager.GetString("AppBar_Intense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions from last thirty days.
        /// </summary>
        public static string AppBar_LastMonth {
            get {
                return ResourceManager.GetString("AppBar_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions from last seven days.
        /// </summary>
        public static string AppBar_LastWeek {
            get {
                return ResourceManager.GetString("AppBar_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see more.
        /// </summary>
        public static string AppBar_SeeMore {
            get {
                return ResourceManager.GetString("AppBar_SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string AppBar_Share {
            get {
                return ResourceManager.GetString("AppBar_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions from today.
        /// </summary>
        public static string AppBar_Today {
            get {
                return ResourceManager.GetString("AppBar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartGuard.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went horribly, horribly wrong! And we couldn&apos;t upload your position. We recommend you check your internet connnection, you know, just in case and try again later..
        /// </summary>
        public static string BroadcastView_BroadcastError {
            get {
                return ResourceManager.GetString("BroadcastView_BroadcastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position updated succesfully!.
        /// </summary>
        public static string BroadcastView_BroadcastSucceeded {
            get {
                return ResourceManager.GetString("BroadcastView_BroadcastSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        public static string BroadcastView_CurrentPosition {
            get {
                return ResourceManager.GetString("BroadcastView_CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My positions.
        /// </summary>
        public static string BroadcastView_MyPositions {
            get {
                return ResourceManager.GetString("BroadcastView_MyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string BroadcastView_Title {
            get {
                return ResourceManager.GetString("BroadcastView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something horrible, horrible happened and we don&apos;t know why. Please try again later..
        /// </summary>
        public static string Facebook_LogIn_Error {
            get {
                return ResourceManager.GetString("Facebook_LogIn_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have succesfully log in to Facebook, now can start using Smartguard..
        /// </summary>
        public static string Facebook_LogIn_Success {
            get {
                return ResourceManager.GetString("Facebook_LogIn_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already logged in to your account. If you press OK you&apos;ll be logged out. Are you sure you want to do this?.
        /// </summary>
        public static string Facebook_LogOut_Question {
            get {
                return ResourceManager.GetString("Facebook_LogOut_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a friend.
        /// </summary>
        public static string FriendAddView_Pivot_AddTitle {
            get {
                return ResourceManager.GetString("FriendAddView_Pivot_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened when you tried to send the request. Check your internet connection and try again later..
        /// </summary>
        public static string FriendAddView_Txt_FriendAddError {
            get {
                return ResourceManager.GetString("FriendAddView_Txt_FriendAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to send an invitation to {0}. Press OK to continue or Cancel to abort the request..
        /// </summary>
        public static string FriendAddView_Txt_FriendAddQuestion {
            get {
                return ResourceManager.GetString("FriendAddView_Txt_FriendAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request sent succesfully!.
        /// </summary>
        public static string FriendAddView_Txt_FriendAddSuccess {
            get {
                return ResourceManager.GetString("FriendAddView_Txt_FriendAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string FriendAddView_Txt_FriendAddTitle {
            get {
                return ResourceManager.GetString("FriendAddView_Txt_FriendAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened when we tried to  get your facebook friends list. Check your internet connection and try again later..
        /// </summary>
        public static string FriendAddView_Txt_FriendDownloadError {
            get {
                return ResourceManager.GetString("FriendAddView_Txt_FriendDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last positions.
        /// </summary>
        public static string FriendInfoView_Title {
            get {
                return ResourceManager.GetString("FriendInfoView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string FriendsView_SeeMore {
            get {
                return ResourceManager.GetString("FriendsView_SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a friend from the list first..
        /// </summary>
        public static string FriendsView_SelectedItemError {
            get {
                return ResourceManager.GetString("FriendsView_SelectedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened when we tried to get the positions from your friends. Check your internet connection and try again later..
        /// </summary>
        public static string FriendsView_Txt_DownloadFriendsError {
            get {
                return ResourceManager.GetString("FriendsView_Txt_DownloadFriendsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string General_Disabled {
            get {
                return ResourceManager.GetString("General_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string General_Enabled {
            get {
                return ResourceManager.GetString("General_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string General_Kilometers {
            get {
                return ResourceManager.GetString("General_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was here on {0} at {1}.
        /// </summary>
        public static string General_LastPositionMessage {
            get {
                return ResourceManager.GetString("General_LastPositionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was my last position..
        /// </summary>
        public static string General_LastPositionTitle {
            get {
                return ResourceManager.GetString("General_LastPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string General_Miles {
            get {
                return ResourceManager.GetString("General_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  near you.
        /// </summary>
        public static string General_NearYou {
            get {
                return ResourceManager.GetString("General_NearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string General_Off {
            get {
                return ResourceManager.GetString("General_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string General_On {
            get {
                return ResourceManager.GetString("General_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be cautious when walking near this zone:.
        /// </summary>
        public static string General_RedZoneWarning {
            get {
                return ResourceManager.GetString("General_RedZoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}
        ///{2}.
        /// </summary>
        public static string General_RedZoneWarning_Message {
            get {
                return ResourceManager.GetString("General_RedZoneWarning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string General_Started {
            get {
                return ResourceManager.GetString("General_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string General_Stopped {
            get {
                return ResourceManager.GetString("General_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concede.
        /// </summary>
        public static string General_Txt_Concede {
            get {
                return ResourceManager.GetString("General_Txt_Concede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follow.
        /// </summary>
        public static string General_Txt_Follow {
            get {
                return ResourceManager.GetString("General_Txt_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revoke.
        /// </summary>
        public static string General_Txt_Revoke {
            get {
                return ResourceManager.GetString("General_Txt_Revoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfollow.
        /// </summary>
        public static string General_Txt_Unfollow {
            get {
                return ResourceManager.GetString("General_Txt_Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to LockScreen settings.
        /// </summary>
        public static string GoToLockScreen {
            get {
                return ResourceManager.GetString("GoToLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re here.
        /// </summary>
        public static string GPS_CurrentPosition {
            get {
                return ResourceManager.GetString("GPS_CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your goal.
        /// </summary>
        public static string GPS_EndPosition {
            get {
                return ResourceManager.GetString("GPS_EndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get directions.
        /// </summary>
        public static string GPS_GetDirections {
            get {
                return ResourceManager.GetString("GPS_GetDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t start Intense Mode if location services are turned off. Please turn them on and try again..
        /// </summary>
        public static string IntenseModeCantStart {
            get {
                return ResourceManager.GetString("IntenseModeCantStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intense Mode has stopped..
        /// </summary>
        public static string IntenseModeOFF {
            get {
                return ResourceManager.GetString("IntenseModeOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intense Mode has started..
        /// </summary>
        public static string IntenseModeON {
            get {
                return ResourceManager.GetString("IntenseModeON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining your position&apos;s address info.
        /// </summary>
        public static string LocationService_Completing {
            get {
                return ResourceManager.GetString("LocationService_Completing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, this is embarassing. We need you to be connected to the internet so you can use SmartGuard. Please check your intenet connection and try again..
        /// </summary>
        public static string LocationService_NoAddressInfo {
            get {
                return ResourceManager.GetString("LocationService_NoAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is embarassing, we couldn&apos;t get your position right now, we blame it on the satellites. Please try again later..
        /// </summary>
        public static string LocationService_NoData {
            get {
                return ResourceManager.GetString("LocationService_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location services are disabled. Please go to your smartphone&apos;s settings and enabled them again..
        /// </summary>
        public static string LocationService_NoService {
            get {
                return ResourceManager.GetString("LocationService_NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining your position.
        /// </summary>
        public static string LocationService_Starting {
            get {
                return ResourceManager.GetString("LocationService_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services.
        /// </summary>
        public static string LocationService_Title {
            get {
                return ResourceManager.GetString("LocationService_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string MainView_Tile_Broadcast {
            get {
                return ResourceManager.GetString("MainView_Tile_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold this tile to quickly upload your position..
        /// </summary>
        public static string MainView_Tile_BroadcastMessage_BroadcastEnabled {
            get {
                return ResourceManager.GetString("MainView_Tile_BroadcastMessage_BroadcastEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold this tile to quickly start Intense Mode..
        /// </summary>
        public static string MainView_Tile_BroadcastMessage_IntenseEnabled {
            get {
                return ResourceManager.GetString("MainView_Tile_BroadcastMessage_IntenseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend&apos;s positions.
        /// </summary>
        public static string MainView_Tile_Friends {
            get {
                return ResourceManager.GetString("MainView_Tile_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string MainView_Tile_Notifications {
            get {
                return ResourceManager.GetString("MainView_Tile_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The place to revoke and concede permissions..
        /// </summary>
        public static string MainView_Tile_Notifications_Message {
            get {
                return ResourceManager.GetString("MainView_Tile_Notifications_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedZones.
        /// </summary>
        public static string MainView_Tile_RedZones {
            get {
                return ResourceManager.GetString("MainView_Tile_RedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to know if that place you want to go is safe?..
        /// </summary>
        public static string MainView_Tile_RedZones_Message {
            get {
                return ResourceManager.GetString("MainView_Tile_RedZones_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions registered from the last thirty days..
        /// </summary>
        public static string Positions_NoPositionsLastMonth {
            get {
                return ResourceManager.GetString("Positions_NoPositionsLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions registered from the last seven days..
        /// </summary>
        public static string Positions_NoPositionsLastSevenDays {
            get {
                return ResourceManager.GetString("Positions_NoPositionsLastSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions registered today..
        /// </summary>
        public static string Positions_NoPositionsToday {
            get {
                return ResourceManager.GetString("Positions_NoPositionsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the position you want to share..
        /// </summary>
        public static string PositionSelectedError {
            get {
                return ResourceManager.GetString("PositionSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app.
        /// </summary>
        public static string RateView_Btn_RateMe {
            get {
                return ResourceManager.GetString("RateView_Btn_RateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the online survey.
        /// </summary>
        public static string RateView_Btn_Survey {
            get {
                return ResourceManager.GetString("RateView_Btn_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have your say.
        /// </summary>
        public static string RateView_Pivot_Title {
            get {
                return ResourceManager.GetString("RateView_Pivot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because your opinion really matters, the SmartGuard team takes serious attention to all possible feedback you give us, that&apos;s why we always read your comments on the reviews. You are helping us make SmartGuard a better app for everyone.
        ///And in that spirit we would really appreciate it if we can steal a minute of your time to fill an online survey that will help us to know what you may want or need in the next app update.
        ///Thank you for using SmartGuard! We care as much as you when beloved ones are involved [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RateView_Txt_Explanation {
            get {
                return ResourceManager.GetString("RateView_Txt_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Red Zone from the list first..
        /// </summary>
        public static string RedZone_SelectedItemError {
            get {
                return ResourceManager.GetString("RedZone_SelectedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Zones.
        /// </summary>
        public static string RedZonesView_Title {
            get {
                return ResourceManager.GetString("RedZonesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description about the zone:.
        /// </summary>
        public static string RedZonesView_UpdateDescription {
            get {
                return ResourceManager.GetString("RedZonesView_UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated zone radio (in meters):.
        /// </summary>
        public static string RedZonesView_UpdateRadius {
            get {
                return ResourceManager.GetString("RedZonesView_UpdateRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered .
        /// </summary>
        public static string RegisteredAt {
            get {
                return ResourceManager.GetString("RegisteredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string RequestsView_PivotIncoming_Title {
            get {
                return ResourceManager.GetString("RequestsView_PivotIncoming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        public static string RequestsView_PivotOutgoing_Title {
            get {
                return ResourceManager.GetString("RequestsView_PivotOutgoing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string RequestsView_Title {
            get {
                return ResourceManager.GetString("RequestsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to {0}  {1}&apos;s positions. Are you sure? If so, press OK to confirm or Cancel to abort the update..
        /// </summary>
        public static string RequestsView_Txt_UpdateFollowingStatus {
            get {
                return ResourceManager.GetString("RequestsView_Txt_UpdateFollowingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to {0} permissions for {1}. Are you sure? If so, press OK to confirm or Cancel to abort the update..
        /// </summary>
        public static string RequestsView_Txt_UpdatePermission {
            get {
                return ResourceManager.GetString("RequestsView_Txt_UpdatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened when we tried to update this friend&apos;s permission. Please check your internet connection and try again later..
        /// </summary>
        public static string RequestView_Txt_UpdatePermissionError {
            get {
                return ResourceManager.GetString("RequestView_Txt_UpdatePermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission updated succesfully!.
        /// </summary>
        public static string RequestView_Txt_UpdatePermissionSuccess {
            get {
                return ResourceManager.GetString("RequestView_Txt_UpdatePermissionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  says:.
        /// </summary>
        public static string Says {
            get {
                return ResourceManager.GetString("Says", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred distance measure:.
        /// </summary>
        public static string SettingsView_DistanceMeasure {
            get {
                return ResourceManager.GetString("SettingsView_DistanceMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intense mode.
        /// </summary>
        public static string SettingsView_IntenseMode {
            get {
                return ResourceManager.GetString("SettingsView_IntenseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When started, your position is updated almost every 10 minutes when you&apos;re outside SmartGuard if you are connected to the internet and your GPS is receiving data..
        /// </summary>
        public static string SettingsView_IntenseMode_Message {
            get {
                return ResourceManager.GetString("SettingsView_IntenseMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockscreen capability:.
        /// </summary>
        public static string SettingsView_LockScreen {
            get {
                return ResourceManager.GetString("SettingsView_LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum positions to download from each friend.
        /// </summary>
        public static string SettingsView_MaxPositions {
            get {
                return ResourceManager.GetString("SettingsView_MaxPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline database.
        /// </summary>
        public static string SettingsView_OfflineDB {
            get {
                return ResourceManager.GetString("SettingsView_OfflineDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, everytime you receive new information, it&apos;s stored as a backup in an offline database so you can check on it when you&apos;re not near a WiFi hotspot or out of your data plan limit..
        /// </summary>
        public static string SettingsView_OfflineDB_Message {
            get {
                return ResourceManager.GetString("SettingsView_OfflineDB_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick broadcast.
        /// </summary>
        public static string SettingsView_QuickBroadcast {
            get {
                return ResourceManager.GetString("SettingsView_QuickBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold tap the Broadcast tile to quickly upload your position..
        /// </summary>
        public static string SettingsView_QuickBroadcast_Message {
            get {
                return ResourceManager.GetString("SettingsView_QuickBroadcast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick intense mode .
        /// </summary>
        public static string SettingsView_QuickIntenseMode {
            get {
                return ResourceManager.GetString("SettingsView_QuickIntenseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the Broacast tile to start Intense mode from the main menu.
        /// </summary>
        public static string SettingsView_QuickIntenseMode_Message {
            get {
                return ResourceManager.GetString("SettingsView_QuickIntenseMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string SettingsView_Txt_Friends {
            get {
                return ResourceManager.GetString("SettingsView_Txt_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsView_Txt_General {
            get {
                return ResourceManager.GetString("SettingsView_Txt_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string SettingsView_Txt_MyPosition {
            get {
                return ResourceManager.GetString("SettingsView_Txt_MyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was seen near {1} on {2} at {3}.
        /// </summary>
        public static string Share_ShareFriendPosition {
            get {
                return ResourceManager.GetString("Share_ShareFriendPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an Email.
        /// </summary>
        public static string ShareView_Email {
            get {
                return ResourceManager.GetString("ShareView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an SMS.
        /// </summary>
        public static string ShareView_SMS {
            get {
                return ResourceManager.GetString("ShareView_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On social networks.
        /// </summary>
        public static string ShareView_SocialNetworks {
            get {
                return ResourceManager.GetString("ShareView_SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share it.
        /// </summary>
        public static string ShareView_Title {
            get {
                return ResourceManager.GetString("ShareView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartGuard&apos;s Background Agent let&apos;s you do a couple of things such as:
        ///- Check your friend&apos;s last activity
        ///- Upload your position even when you&apos;re outside SmartGuard
        ///- Check news about new red zones around you..
        /// </summary>
        public static string SmartGuardBackgroundAgent {
            get {
                return ResourceManager.GetString("SmartGuardBackgroundAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near .
        /// </summary>
        public static string Txt_Near {
            get {
                return ResourceManager.GetString("Txt_Near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Views_Friends {
            get {
                return ResourceManager.GetString("Views_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Views_List {
            get {
                return ResourceManager.GetString("Views_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Views_Map {
            get {
                return ResourceManager.GetString("Views_Map", resourceCulture);
            }
        }
    }
}
